In [1]:
import tensorflow as tf

# creation and exploring tensors

In [3]:
scala=tf.constant(7)
scala

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scala.ndim

0

In [ ]:
vector=tf.constant([1,2,3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix=tf.constant(([1,2],[3,4]))
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [12]:
tensor=tf.constant([[[1,2,3],[4,5,6]],
                    [[7,8,9],[10,11,12]],
                    [[1,2,3],[4,5,6]]]
                    )
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]], dtype=int32)>

In [11]:
tensor.ndim

3

In [6]:
changeable_vector=tf.Variable([4,7])
unchangeable_vector=tf.constant([5,8])
changeable_vector,unchangeable_vector

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 8], dtype=int32)>)

In [10]:
changeable_vector[0].assign(7)
changeable_vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

1️⃣ What’s the problem we’re solving?
We want a neural network to look at an image (say, a photo of food) and decide:

Is it ramen 🍜 or spaghetti 🍝?

2️⃣ Step 1: Turn images into numbers
Computers don’t “see” pictures like humans.

A picture is really just a grid of pixels, and each pixel has numbers (color values).

We’ll encode the image into a tensor — basically a fancy word for an array of numbers.

3️⃣ Step 2: Pass numbers into the neural network
The input layer of the network takes those numbers (tensor).

Inside the network are weights — these are the “knobs” the network can turn to recognize patterns.

At first, the network doesn’t know anything about ramen or spaghetti.

4️⃣ Step 3: Initialization
Initialize just means “give the weights a starting value.”

Usually, they are random numbers.

At this stage, the network is basically guessing.

5️⃣ Step 4: Learning
We show the network an image and the correct answer (label).

It makes a guess based on its random weights → usually wrong at first.

Then it tweaks the weights slightly so next time it’s a bit closer to the right answer.

This tweak process happens over and over (many examples, many tweaks).

6️⃣ Step 5: Improvement
The more examples it sees, the better it adjusts the weights.

Over time, the network’s patterns (features it looks for) match the important parts of the data:

Maybe shape of noodles

Color of broth or sauce

Eventually, it starts getting predictions right.\\

## gernerate random tensors
seed=42 means: “Always give me the same random numbers each time I run this code.”
(This is useful so results are reproducible.)


In [14]:
random1=tf.random.Generator.from_seed(42)
random2=tf.random.Generator.from_seed(42)
random1=tf.random.uniform(shape=(3,2))
random2=tf.random.normal(shape=(3,2))
random1,random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.6957501 , 0.5004767 ],
        [0.9501687 , 0.21089411],
        [0.639526  , 0.8676683 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.64080817,  0.02814939],
        [-0.03213574, -1.0064155 ],
        [-1.4653335 ,  1.5829277 ]], dtype=float32)>)

shuffle the order of elements

In [35]:
not_shuffled=tf.constant([[1,2,3]
                         ,[4,5,6]
                         ,[7,8,9]])
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [43]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]], dtype=int32)>

Getting information from your tensors (tensor attributes)

In [15]:
test=tf.zeros(shape=(2,3,4,5))
test

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [18]:
#get informations
print("nombre de dimensions :",test.ndim)
print("shape of tensor :",test.shape)
print("element's number :",tf.size(test).numpy())


nombre de dimensions : 4
shape of tensor : (2, 3, 4, 5)
element's number : 120


In [11]:
ts=tf.Variable(([1,2],[3,4]))
td=tf.multiply(ts,10)
td,ts

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>)

In [12]:
#affichage de valeurs absolues
ts=tf.Variable(([-1,-2],[-3,-4]))
tf.abs(ts)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

find the position of max/min in a tensor

In [9]:
tf.random.set_seed(42)
M=tf.random.uniform(shape=[50])
print(M)
tf.argmax(M) , M[tf.argmax(M)]


tf.Tensor(
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
 0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
 0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
 0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
 0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
 0.9671384  0.06870162 0.79873943 0.66028714 0.5871513  0.16461694
 0.7381023  0.32054043], shape=(50,), dtype=float32)


(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>)

one hot encoding

In [17]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=4, on_value="A",off_value="B")

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

🔑 Key Takeaway:

Numpy arrays → CPU only.

Tensors → Can run on CPU, GPU, or TPU.

For deep learning: GPU/TPU acceleration is critical for speed.

CUDA = what allows NVIDIA GPUs to work with ML frameworks.

